version: 0.1
            
phases:

  install: 
    commands:
      - echo Nothing to do in the install phase ...

  pre_build: 
    commands:
      - echo Nothing to do in the pre_build phase ...

  build:
    commands:
      - echo Nothing to do in the build phase, maybe ...

artifacts:
  files:
    - buildspec.yml
    - config/*
    - cloudformation/*
