version: 0.1
            
phases:

  install: 
    commands:
      - echo Nothing to do in the install phase ...

  pre_build: 
    commands:
      - echo Nothing to do in the pre_build phase ...

  build:
    commands:
      - aws cloudformation package --template-file ./cloudformation/infrastructure.yml --s3-bucket test-pipeline-ivan --output-template-file ./packaged-template
      
      - aws cloudformation deploy  --template-file  packaged-template --stack-name changeset-infra-ivan --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --output table --fail-on-empty-changeset

      - aws cloudformation deploy  --template-file  packaged-template --stack-name changeset-infra-ivan --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --output table --fail-on-empty-changeset --no-execute-changeset
      
artifacts:
  files:
    - packaged-template
