Description: >

    Example Infrastructure for a Go Application.
    This template will deploy a highly available Auto Scaling Group of EC2 instances with the CodeDeploy
    agent installed ready for application deployments. It will also deploy a VPC with public and private 
    subnets. An Application Load Balancer is placed in the public subnets, which forwards traffic to the
    application servers in the private subnets. NAT Gateways are deployed in each AZ to facilitate outbound
    traffic from the application servers to the internet.

Parameters:

    # The following parameters are set dynamically by AWS CodePipeline 

    EnvironmentName:
        Type: String
        Default: test
    # All parameters below can be overridden on a per environment basis in config/*

    Username:
        Description: Please enter username
        Type: String
        Default: anonymous

Resources:

  MyEIP:
    Type: 'AWS::EC2::EIP'

Outputs: 
    HelloWorld: 
        Description: test
        Value: !Sub Hello, ${Username}
