Description: Test

Resources:
    SubTest:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: subtest.yaml
            Parameters:
                EnvironmentName: test

